FROM nginx/unit:1.28.0-python3.10

WORKDIR /vet_app

COPY . /vet_app

RUN pip install -r /vet_app/requirements.txt

CMD ["uvicorn","app.main:app","--host","0.0.0.0", "--port","80","--proxy-headers"]

EXPOSE 80

# docker run -d --name <name-container> -p 8000:80 <name-image>